/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.boston.employeemanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Zuko
 */
public class AdminPortal extends javax.swing.JFrame {
    
    DefaultTableModel model;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    //string user: root
    //string password: Kwanelezukotola3
    
    public AdminPortal() {
        initComponents();
        //model = (DefaultTableModel) tblInfo.getModel();
    }
        
        public void insert_values(String First_Name,String Last_Name,String Job_Title,String Date_Of_Birth, String Phone_Number){
		
            
                //DB CONNECTION
		DB_Connection obj_DB_Connection=new DB_Connection();
		java.sql.Connection connection=obj_DB_Connection.get_connection();
		
		java.sql.PreparedStatement ps=null;		
		
		try {
			
		String query= "insert into * Employee_Information (First_Name, Last_Name, ,Job_Title, Date_Of_Birth, Phone_Number) values(?,?,?,?,?,?,?,?,?)";
		 ps=connection.prepareStatement(query);
		 ps.setString(1, First_Name);
		 ps.setString(2, Last_Name);
                 ps.setString(3, Job_Title);
                 ps.setString(4, Date_Of_Birth);
                 ps.setString(5, Phone_Number);
		 
		 ps.executeUpdate();
		 
	 
		} catch (Exception e) {
			System.err.println(e);
		}
		 
	}
        

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEmployeeInformation = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblLN = new javax.swing.JLabel();
        lblJT = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPN = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        txtJT = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPN = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();
        PnlAdditional = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Portal");
        setBounds(new java.awt.Rectangle(870, 750, 450, 450));
        setLocation(new java.awt.Point(550, 25));
        setMinimumSize(new java.awt.Dimension(870, 750));
        setName("Admin Portal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(870, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbEmployeeInformation.setBackground(new java.awt.Color(102, 102, 102));
        lbEmployeeInformation.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lbEmployeeInformation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEmployeeInformation.setText("Employee Information");
        getContentPane().add(lbEmployeeInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        lblFN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFN.setText("First Name");
        lblFN.setToolTipText("");
        getContentPane().add(lblFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblLN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLN.setText("Last Name");
        getContentPane().add(lblLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblJT.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblJT.setText("Job Tiitle");
        getContentPane().add(lblJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblDOB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDOB.setText("Date Of Birth");
        getContentPane().add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblPN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblPN.setText("Phone Number");
        getContentPane().add(lblPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtFN.setForeground(new java.awt.Color(102, 102, 102));
        txtFN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        txtLN.setForeground(new java.awt.Color(102, 102, 102));
        txtLN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

        txtJT.setForeground(new java.awt.Color(102, 102, 102));
        txtJT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJTActionPerformed(evt);
            }
        });
        getContentPane().add(txtJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, -1));

        txtDOB.setForeground(new java.awt.Color(102, 102, 102));
        txtDOB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, -1));

        txtPN.setForeground(new java.awt.Color(102, 102, 102));
        txtPN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, -1));

        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtUsername.setMaximumSize(new java.awt.Dimension(2, 18));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, -1));

        txtPassword.setMaximumSize(new java.awt.Dimension(2, 18));
        txtPassword.setMinimumSize(new java.awt.Dimension(2, 18));
        txtPassword.setPreferredSize(new java.awt.Dimension(2, 18));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 160, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/boston/employeemanagement/profile-icon-illustration-user-profile-computer-icons-girl-customer-avatar-png-clip-art.png"))); // NOI18N
        Background.setText("jLabel10");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 470));

        PnlAdditional.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.setMinimumSize(new java.awt.Dimension(78, 25));
        btnAdd.setPreferredSize(new java.awt.Dimension(60, 20));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setPreferredSize(new java.awt.Dimension(78, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setPreferredSize(new java.awt.Dimension(78, 25));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDelete2.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDelete2.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete2.setText("Delete All");
        btnDelete2.setBorder(null);
        btnDelete2.setPreferredSize(new java.awt.Dimension(78, 25));
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(102, 102, 102));
        btnCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setPreferredSize(new java.awt.Dimension(78, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSC.setBackground(new java.awt.Color(102, 102, 102));
        btnSC.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSC.setForeground(new java.awt.Color(255, 255, 255));
        btnSC.setText("Salary Calculate");
        btnSC.setBorder(null);
        btnSC.setMaximumSize(new java.awt.Dimension(110, 30));
        btnSC.setMinimumSize(new java.awt.Dimension(110, 30));
        btnSC.setPreferredSize(new java.awt.Dimension(110, 30));
        btnSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblInfo.setBackground(new java.awt.Color(102, 102, 102));
        tblInfo.setForeground(new java.awt.Color(255, 255, 255));
        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "Last Name", "Job Title", "Date Of Birth", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout PnlAdditionalLayout = new javax.swing.GroupLayout(PnlAdditional);
        PnlAdditional.setLayout(PnlAdditionalLayout);
        PnlAdditionalLayout.setHorizontalGroup(
            PnlAdditionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdditionalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PnlAdditionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlAdditionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PnlAdditionalLayout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        PnlAdditionalLayout.setVerticalGroup(
            PnlAdditionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAdditionalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PnlAdditionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        getContentPane().add(PnlAdditional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 870, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJTActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                
                DB_Connection obj_DB_Connection=new DB_Connection();
		java.sql.Connection connection=obj_DB_Connection.get_connection();java.sql.PreparedStatement ps=null;		
		
		try {
			
		String query= "insert into * Employee_Information (First_Name, Last_Name, ,Job_Title, Date_Of_Birth, Phone_Number) values(?,?,?,?,?,?,?,?,?)";
		 ps=connection.prepareStatement(query);
		 
		 model = (DefaultTableModel) tblInfo.getModel();
		 ps.executeUpdate();
		 
	 
		} catch (Exception e) {
			System.err.println(e);
		}
                
                    //ADD INFORMATION TO LIVE DATABASE BEFORE ADDING TO THE TABLE
                    
        try{
            model.insertRow(model.getRowCount(),new Object[]{txtFN.getText(),txtDOB.getText(),txtLN.getText(),txtJT.getText(),txtPN.getText()});

            JOptionPane.showMessageDialog(null, "Great, The Employees Information has been added!");
            txtFN.setText(null);
            txtLN.setText(null);
            txtJT.setText(null);
            txtDOB.setText(null);
            txtPN.setText(null);
            txtUsername.setText(null);            
            txtPassword.setText(null);

                            
                               
        }
        catch (Exception e){
         JOptionPane.showMessageDialog(null, "Information, Couldnt be added to Database FA1. Please Connect and Attempt Last Request Again");                               
        }
//                         
//
//                            //THIS IS THE ALTERNATIVE CONNECTION TO MYSQL DATABASE
//                         
//        try{
//    String sql = "INSERT INTO fa1.Employee_Information"
//            + "(idEmployee_Information, First Name, Last Name, Job Title, Date Of Birth, Phone Number)"
//            +"VALUES (?,?,?,?,?,?)";
//            
//    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fa1/", "root", "Kwanelezukotola3");
//    pst = (PreparedStatement) con.prepareStatement(sql);
//    pst.setString(1, txtFN.getText());
//    pst.setString(2, txtLN.getText());
//    pst.setString(3, txtJT.getText());
//    pst.setString(4, txtDOB.getText());
//    pst.setString(5, txtPN.getText());
//    pst.executeUpdate();
//    
//    JOptionPane.showMessageDialog(null, "Successful");
//}
// catch (HeadlessException | SQLException ex){
//    JOptionPane.showMessageDialog(null, ex);
//    
//}		 	
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCActionPerformed
        EmployeeCalculator EmployeeCalculator = new EmployeeCalculator();
        EmployeeCalculator.show();
        this.show(false);
      // TODO add your handling code here:
    }//GEN-LAST:event_btnSCActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
tblInfo.setModel(new DefaultTableModel(null,new String[]{"First Name", "Last Name","Job Title","Date Of Birth","Phone Number"}));
// TODO add your handling code here:
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
int i = tblInfo.getSelectedRow();
DefaultTableModel model = (DefaultTableModel)tblInfo.getModel();
if(i > 0)
{
    model.setValueAt(txtFN.getText(), i, 0);
    model.setValueAt(txtLN.getText(), i, 1);
    model.setValueAt(txtJT.getText(), i, 2);
    model.setValueAt(txtDOB.getText(), i, 3);
    model.setValueAt(txtPN.getText(), i, 4);
}
    else{
 JOptionPane.showMessageDialog(null, "Couldnt connect to Database at this time");   
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfoMouseClicked
int SelectedRow = tblInfo.getSelectedRow();
DefaultTableModel model = (DefaultTableModel)tblInfo.getModel();
txtFN.setText(model.getValueAt(SelectedRow, 0).toString());
txtLN.setText(model.getValueAt(SelectedRow, 1).toString());
txtJT.setText(model.getValueAt(SelectedRow, 2).toString());
txtDOB.setText(model.getValueAt(SelectedRow, 3).toString());
txtPN.setText(model.getValueAt(SelectedRow, 4).toString());
    }//GEN-LAST:event_tblInfoMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
DefaultTableModel model = (DefaultTableModel)tblInfo.getModel();
try{
    int SelectedRowIndex = tblInfo.getSelectedRow();
    model.removeRow(SelectedRowIndex);
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel PnlAdditional;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnSC;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmployeeInformation;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblJT;
    private javax.swing.JLabel lblLN;
    private javax.swing.JLabel lblPN;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtJT;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtPN;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
