/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.boston.employeemanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zuko
 */
public class EmployeeCalculator extends javax.swing.JFrame {
    DefaultTableModel model;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form EmployeeCalculator
     */
    public EmployeeCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblBSalary = new javax.swing.JLabel();
        lblDept = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        txtFN = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtBSalary = new javax.swing.JTextField();
        txtDept = new javax.swing.JTextField();
        lblOvertime = new javax.swing.JLabel();
        lblMed = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        txtOvertime = new javax.swing.JTextField();
        txtMed = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        txtOther = new javax.swing.JTextField();
        lblTO = new javax.swing.JLabel();
        lblRPH = new javax.swing.JLabel();
        lblOne = new javax.swing.JLabel();
        lblTwo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalculate = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblThree = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salary Calculator");
        setBounds(new java.awt.Rectangle(870, 750, 450, 450));
        setLocation(new java.awt.Point(550, 25));
        setMaximumSize(new java.awt.Dimension(870, 750));
        setMinimumSize(new java.awt.Dimension(870, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Salary Calculation");
        jPanel1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 870, -1));

        lblEmpID.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpID.setText("Employee ID");
        lblEmpID.setMaximumSize(new java.awt.Dimension(75, 20));
        lblEmpID.setMinimumSize(new java.awt.Dimension(75, 20));
        lblEmpID.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblFN.setForeground(new java.awt.Color(255, 255, 255));
        lblFN.setText("First Name");
        lblFN.setMaximumSize(new java.awt.Dimension(75, 20));
        lblFN.setMinimumSize(new java.awt.Dimension(75, 20));
        lblFN.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblSurname.setText("Surname");
        lblSurname.setMaximumSize(new java.awt.Dimension(75, 20));
        lblSurname.setMinimumSize(new java.awt.Dimension(75, 20));
        lblSurname.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblDOB.setText("Date Of Birth");
        lblDOB.setMaximumSize(new java.awt.Dimension(75, 20));
        lblDOB.setMinimumSize(new java.awt.Dimension(75, 20));
        lblDOB.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        lblBSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblBSalary.setText("Basic Salary");
        lblBSalary.setMaximumSize(new java.awt.Dimension(75, 20));
        lblBSalary.setMinimumSize(new java.awt.Dimension(75, 20));
        lblBSalary.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblBSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        lblDept.setForeground(new java.awt.Color(255, 255, 255));
        lblDept.setText("Department");
        lblDept.setMaximumSize(new java.awt.Dimension(75, 20));
        lblDept.setMinimumSize(new java.awt.Dimension(75, 20));
        lblDept.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        txtEmpID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpID.setBorder(null);
        txtEmpID.setMaximumSize(new java.awt.Dimension(150, 24));
        txtEmpID.setMinimumSize(new java.awt.Dimension(150, 24));
        txtEmpID.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        txtFN.setBackground(new java.awt.Color(255, 255, 255));
        txtFN.setBorder(null);
        txtFN.setMaximumSize(new java.awt.Dimension(150, 24));
        txtFN.setMinimumSize(new java.awt.Dimension(150, 24));
        txtFN.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        txtSurname.setBackground(new java.awt.Color(255, 255, 255));
        txtSurname.setBorder(null);
        txtSurname.setMaximumSize(new java.awt.Dimension(150, 24));
        txtSurname.setMinimumSize(new java.awt.Dimension(150, 24));
        txtSurname.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        txtDOB.setBackground(new java.awt.Color(255, 255, 255));
        txtDOB.setBorder(null);
        txtDOB.setMaximumSize(new java.awt.Dimension(150, 24));
        txtDOB.setMinimumSize(new java.awt.Dimension(150, 24));
        txtDOB.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        txtBSalary.setBackground(new java.awt.Color(255, 255, 255));
        txtBSalary.setBorder(null);
        txtBSalary.setMaximumSize(new java.awt.Dimension(150, 24));
        txtBSalary.setMinimumSize(new java.awt.Dimension(150, 24));
        txtBSalary.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtBSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        txtDept.setBackground(new java.awt.Color(255, 255, 255));
        txtDept.setBorder(null);
        txtDept.setMaximumSize(new java.awt.Dimension(150, 24));
        txtDept.setMinimumSize(new java.awt.Dimension(150, 24));
        txtDept.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        lblOvertime.setForeground(new java.awt.Color(255, 255, 255));
        lblOvertime.setText("Overtime");
        lblOvertime.setMaximumSize(new java.awt.Dimension(75, 20));
        lblOvertime.setMinimumSize(new java.awt.Dimension(75, 20));
        lblOvertime.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        lblMed.setForeground(new java.awt.Color(255, 255, 255));
        lblMed.setText("Medical");
        lblMed.setMaximumSize(new java.awt.Dimension(75, 20));
        lblMed.setMinimumSize(new java.awt.Dimension(75, 20));
        lblMed.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        lblBonus.setForeground(new java.awt.Color(255, 255, 255));
        lblBonus.setText("Bonus");
        lblBonus.setMaximumSize(new java.awt.Dimension(75, 20));
        lblBonus.setMinimumSize(new java.awt.Dimension(75, 20));
        lblBonus.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        lblOther.setForeground(new java.awt.Color(255, 255, 255));
        lblOther.setText("Other");
        lblOther.setMaximumSize(new java.awt.Dimension(75, 20));
        lblOther.setMinimumSize(new java.awt.Dimension(75, 20));
        lblOther.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(lblOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        txtOvertime.setBackground(new java.awt.Color(255, 255, 255));
        txtOvertime.setBorder(null);
        txtOvertime.setMaximumSize(new java.awt.Dimension(150, 24));
        txtOvertime.setMinimumSize(new java.awt.Dimension(150, 24));
        txtOvertime.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        txtMed.setBackground(new java.awt.Color(255, 255, 255));
        txtMed.setBorder(null);
        txtMed.setMaximumSize(new java.awt.Dimension(150, 24));
        txtMed.setMinimumSize(new java.awt.Dimension(150, 24));
        txtMed.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        txtBonus.setBackground(new java.awt.Color(255, 255, 255));
        txtBonus.setBorder(null);
        txtBonus.setMaximumSize(new java.awt.Dimension(150, 24));
        txtBonus.setMinimumSize(new java.awt.Dimension(150, 24));
        txtBonus.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        txtOther.setBackground(new java.awt.Color(255, 255, 255));
        txtOther.setBorder(null);
        txtOther.setMaximumSize(new java.awt.Dimension(150, 24));
        txtOther.setMinimumSize(new java.awt.Dimension(150, 24));
        txtOther.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel1.add(txtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        lblTO.setForeground(new java.awt.Color(255, 255, 255));
        lblTO.setText("Total Overtime");
        lblTO.setMaximumSize(new java.awt.Dimension(90, 20));
        lblTO.setMinimumSize(new java.awt.Dimension(90, 20));
        lblTO.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(lblTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        lblRPH.setForeground(new java.awt.Color(255, 255, 255));
        lblRPH.setText("Rate Per Hour");
        lblRPH.setMaximumSize(new java.awt.Dimension(90, 20));
        lblRPH.setMinimumSize(new java.awt.Dimension(90, 20));
        lblRPH.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(lblRPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        lblOne.setForeground(new java.awt.Color(255, 0, 102));
        lblOne.setText("______________________________");
        lblOne.setToolTipText("");
        jPanel1.add(lblOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 220, -1));

        lblTwo.setForeground(new java.awt.Color(255, 0, 102));
        lblTwo.setText("______________________________");
        jPanel1.add(lblTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblCalculate.setBackground(new java.awt.Color(102, 102, 102));
        tblCalculate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tblCalculate.setForeground(new java.awt.Color(255, 255, 255));
        tblCalculate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Surname", "Date Of Birth", "Basic Salary", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCalculate.setMaximumSize(new java.awt.Dimension(525, 500));
        tblCalculate.setMinimumSize(new java.awt.Dimension(525, 500));
        tblCalculate.setPreferredSize(new java.awt.Dimension(525, 500));
        tblCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCalculateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCalculate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 500, 520));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnClear.setMaximumSize(new java.awt.Dimension(80, 25));
        btnClear.setMinimumSize(new java.awt.Dimension(80, 25));
        btnClear.setPreferredSize(new java.awt.Dimension(80, 25));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, -1, -1));

        btnCalculate.setBackground(new java.awt.Color(102, 102, 102));
        btnCalculate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnCalculate.setMaximumSize(new java.awt.Dimension(80, 25));
        btnCalculate.setMinimumSize(new java.awt.Dimension(80, 25));
        btnCalculate.setPreferredSize(new java.awt.Dimension(80, 25));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, -1, -1));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnSave.setMaximumSize(new java.awt.Dimension(80, 25));
        btnSave.setMinimumSize(new java.awt.Dimension(80, 25));
        btnSave.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, -1, -1));

        lblThree.setForeground(new java.awt.Color(255, 0, 102));
        lblThree.setText("______________________________");
        jPanel1.add(lblThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 110, 20));

        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtEmpID.setText(null);
    txtFN.setText(null);
    txtSurname.setText(null);
    txtDOB.setText(null);
    txtBSalary.setText(null);
    txtDept.setText(null);
    txtOvertime.setText(null);
    txtMed.setText(null);
    txtBonus.setText(null);
    txtOther.setText(null);
    lbl1.setText(null);
    lbl2.setText(null);
    
    try{
    int SelectedRowIndex = tblCalculate.getSelectedRow();
    model.removeRow(SelectedRowIndex);
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, "Please select Table to be deleted");
}
    
    JOptionPane.showMessageDialog(null, "Your Search is Cleared");
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                DB_Connection obj_DB_Connection=new DB_Connection();
		java.sql.Connection connection=obj_DB_Connection.get_connection();java.sql.PreparedStatement ps=null;		
		
		try {
			
		String query= "insert into * salary_calculator (First Name, Surname, ,Job_Title, Date Of Birth, Basic Salary, Department) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    ps=connection.prepareStatement(query);
		 
                model = (DefaultTableModel) tblCalculate.getModel();
		ps.executeUpdate();
		 
	 
		} catch (Exception e) {
			System.err.println(e);
		}
                // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
int Overtime = Integer.parseInt(txtOvertime.getText());
int Medical = Integer.parseInt(txtMed.getText()); 
int Bonus = Integer.parseInt(txtBonus.getText());
int Other = Integer.parseInt(txtOther.getText());

double a = Overtime + Medical + Bonus + Other;
double b = (a /60);
lbl1.setText("" + a);
lbl2.setText("" + b);


model = (DefaultTableModel) tblCalculate.getModel();
try{
            model.insertRow(model.getRowCount(),new Object[]{txtEmpID.getText(),txtFN.getText(),txtSurname.getText(),txtDOB.getText(),txtBSalary.getText(),txtDept.getText()});

            JOptionPane.showMessageDialog(null, "Great, The Employees Information has been added!");
            txtEmpID.setText(null);
            txtFN.setText(null);
            txtSurname.setText(null);
            txtDOB.setText(null);
            txtBSalary.setText(null);
            txtDept.setText(null);            
            
}
            catch (Exception e){
         JOptionPane.showMessageDialog(null, "Information, Couldnt be added to Table");                               
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void tblCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCalculateMouseClicked
int SelectedRow = tblCalculate.getSelectedRow();
DefaultTableModel model = (DefaultTableModel)tblCalculate.getModel();
txtEmpID.setText(model.getValueAt(SelectedRow, 0).toString());
txtFN.setText(model.getValueAt(SelectedRow, 1).toString());
txtSurname.setText(model.getValueAt(SelectedRow, 2).toString());
txtDOB.setText(model.getValueAt(SelectedRow, 3).toString());
txtBSalary.setText(model.getValueAt(SelectedRow, 4).toString());
txtDept.setText(model.getValueAt(SelectedRow, 5).toString());  
// TODO add your handling code here:
    }//GEN-LAST:event_tblCalculateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblBSalary;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMed;
    private javax.swing.JLabel lblOne;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblOvertime;
    private javax.swing.JLabel lblRPH;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTO;
    private javax.swing.JLabel lblThree;
    private javax.swing.JLabel lblTwo;
    private javax.swing.JTable tblCalculate;
    private javax.swing.JTextField txtBSalary;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtMed;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtOvertime;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
